### ISSUE TITLE
feat: Backup links

### ISSUE THREAD

**Issue by ofou** [henb13/jre-missing#3]
It'd be awesome to have backup links for deleted episodes.

**Comment by strager** [comment]
@ofou Do you have a site which stores backups?

**Comment by ofou** [comment]
Unfortunately, no 😪, but I just found [#1197](https://www.mixcloud.com/TheJoeRoganExperience/1197-michael-malice/) on Mixcloud. I imagine there should be a bunch of places where to find the episodes. If you agree this could be a feat. I don't mind trying to help, finding sources.

**Comment by danetuso** [comment]
Groups of episodes are uploaded on archive.org. They can still be accessed directly. For instance, #1197 was removed from spotify and youtube, but is available here: 
https://archive.org/details/jre-1095-1250/JRE_1095-1250/Joe+Rogan+Experience+%231197+-+Michael+Malice.mp4

The URL format seems to be consistent between groups of videos at first glance.
All of them that are available can be found here: (1-1558)
https://archive.org/details/jre-001-837
https://archive.org/details/jre-838-1094
https://archive.org/details/jre-1095-1250
https://archive.org/details/jre-1251-1476
https://archive.org/details/joe-rogan-experience-1477-present

I am not sure what to do for episodes more recent than #1558. (The most recent episode is 1772) Maybe someone else knows of another archive.

**Comment by henb13** [comment]
Thank you for your suggestion, but this would be outside the scope and intention of this website.
