### ISSUE TITLE
other missing episodes

### ISSUE THREAD

**Issue by shartattack** [henb13/jre-missing#5]
Unable to find guests Alex Grey [3 episodes]. Bruce Damer phd, Dennis McKenna phd.  I think Paul Stamets is already listed?

**Comment by henb13** [comment]
Hi, I am able to find all those episode when searching for them in Spotify.

**Comment by shartattack** [comment]
Where r they posted??

**Comment by shartattack** [comment]
3 episodes w Alex grey please send links when able.  Dave
